---
- name: --- Update apt cache ---
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: --- Install base packages ---
  ansible.builtin.apt:
    name: [ca-certificates, curl, tar, gnupg, apt-transport-https, python3-apt]
    state: present
